resources:
- ../../base/namespace
- ../../base/core-api
- ../../base/postgres
- ../../base/quiz
- ../../base/payment-api
- ../../base/notification-service
- ../../base/portal
namespace: apollo11
# namePrefix: dev-
# nameSuffix: "-001"
# labels:
#   - pairs:
#       app: apollo11
#     includeSelectors: true 
# commonAnnotations:
#   oncallPager: 800-555-1212