apiVersion: batch/v1
kind: CronJob
metadata:
  name: report-generator
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: report-generator
            image: localhost:5000/apollo11-report-service:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres:5432/apollo11"
          restartPolicy: OnFailure
