apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apollo11
  name: quiz-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
        - name: quiz-service
          image: local-registry:5000/apollo11-quiz-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@postgres:5432/apollo11"
  
